pull_request_rules:
  - name: Automatically merge when TeamCity build succeeds
    conditions:
      - check-success = TeamCity  # Change this to match your TeamCity check name
      - "#approved-reviews-by >= 1"
    actions:
      merge:
        method: merge